services:
  db:
    image: pgvector/pgvector:pg16
    container_name: clip_vector_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clip_search
    volumes:
      - clip_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: clip_search_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/clip_search
      - IMAGES_DIR=/images
      - MODEL_DIR=/models
    volumes:
      - ..:/src
      - ../Images:/images
      - ../ClipVit:/models
    depends_on:
      - db

volumes:
  clip_pgdata:
