services:
  moonvit-search:
    build: .
    image: moonvit-search:latest
    container_name: moonvit_search_app
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=62.72.42.158
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASS=root
      - DB_NAME=clip_search
      - IMAGES_DIR=/app/Images
      - MODEL_DIR=/app/models/moonshotaiMoonViT-SO-400M
    volumes:
      - ./Images:/app/Images:ro
      - ./models:/app/models:ro
    restart: always
